/** Versioned operator-authorized policy. These are release constants, not tuning knobs. */
export const POLICY_VERSION = "fixed-risk-v2";
export const MONEY_MANAGEMENT = {
  setupRiskPercent: "1",
  dailyLossLimitPercent: "5",
  drawdownLimitPercent: "5",
} as const;
export const FIXED_DEFAULTS = {
  LOG_LEVEL: "info",
  LIVE_TRADING_ENABLED: "false",
  LIVE_TRADING_ACKNOWLEDGEMENT: "",
  PAUSE_NEW_ANALYSES: "false",
  AUTOMATIC_ANALYSIS_COMPLETED_LIMIT: "0",
  AUTOMATIC_ANALYSIS_COMPLETED_BASELINE: "0",
  AUTOMATIC_DEMO_CLOSED_TRADE_LIMIT: "0",
  AUTOMATIC_DEMO_CLOSED_TRADE_BASELINE: "0",
  SHUTDOWN_CANCEL_PENDING: "true",
  RUNTIME_CONTROL_POLL_SECONDS: "2",
  ANALYSIS_INTERVAL_SECONDS: "5",
  ANALYSIS_SCHEDULER_LEAD_MS: "1000",
  AUTOMATIC_ANALYSIS_START_WINDOW_SECONDS: "10",
  AUTOMATIC_ANALYSIS_STALL_SECONDS: "360",
  MODEL_MINIMUM_CALL_BUDGET_SECONDS: "40",
  MODEL_POST_RESPONSE_RESERVE_SECONDS: "5",
  BLOCK_ON_MANUAL_SYMBOL_ORDERS: "true",
  BLOCK_ON_MANUAL_SYMBOL_POSITIONS: "true",
  CTRADER_RECONNECT_MIN_MS: "1000",
  CTRADER_RECONNECT_MAX_MS: "30000",
  CTRADER_REQUEST_TIMEOUT_MS: "10000",
  DEMO_EXECUTION_RECOVERY_INTERVAL_SECONDS: "15",
  BARS_15M: "300",
  BARS_5M: "500",
  BARS_1M: "600",
  USE_COMPLETED_CANDLES_ONLY: "true",
  MODEL_PAYLOAD_MODE: "compact",
  MODEL_FULL_CANDLE_LIMIT_15M: "300",
  MODEL_FULL_CANDLE_LIMIT_5M: "500",
  MODEL_FULL_CANDLE_LIMIT_1M: "600",
  MODEL_COMPACT_RAW_TAIL_15M: "12",
  MODEL_COMPACT_RAW_TAIL_5M: "18",
  MODEL_COMPACT_RAW_TAIL_1M: "30",
  MAX_CANDLE_SKEW_MS: "5000",
  ATR_PERIOD: "15",
  EMA_FAST_PERIOD: "5",
  EMA_SLOW_PERIOD: "19",
  ADX_ENABLED: "true",
  ADX_PERIOD: "14",
  RSI_ENABLED: "true",
  RSI_PERIOD: "14",
  BOLLINGER_ENABLED: "false",
  BOLLINGER_PERIOD: "20",
  BOLLINGER_STDDEV: "2",
  PERFORMANCE_MINIMUM_SAMPLES: "20",
  PERFORMANCE_DECAY: "0.97",
  PERFORMANCE_ROLLING_TRADES: "200",
  SWING_PIVOT_LEFT: "3",
  SWING_PIVOT_RIGHT: "3",
  ORDER_BOOK_DEPTH: "4",
  ORDER_BOOK_SNAPSHOT_TIMEOUT_MS: "3000",
  ORDER_BOOK_MAX_AGE_MS: "3000",
  SYMBOL_METADATA_MAX_AGE_MS: "86400000",
  MAX_QUOTE_AGE_MS: "3000",
  LOCAL_MARKET_RECORDING_ENABLED: "true",
  LOCAL_MARKET_RECORD_DIRECTORY: ".runtime/market-data",
  LOCAL_MARKET_RECORD_INTERVAL_MS: "250",
  LOCAL_MARKET_RECORD_SEGMENT_SECONDS: "300",
  LOCAL_MARKET_RECORD_MAX_SEGMENTS: "2016",
  AI_MODEL: "gpt-6-astra/u64",
  AI_API_STYLE: "responses",
  AI_TIMEOUT_MS: "45000",
  AI_MAX_RETRIES: "0",
  AI_TEMPERATURE: "",
  AI_SCHEMA_VERSION: "2.1",
  MIN_EXPECTED_NET_TO_FEES_RATIO: "1",
  AI_MAX_OUTPUT_TOKENS: "3000",
  AI_REASONING_EFFORT: "",
  AI_CIRCUIT_BREAKER_FAILURES: "3",
  AI_CIRCUIT_BREAKER_RESET_SECONDS: "300",
  BASE_RISK_PERCENT: MONEY_MANAGEMENT.setupRiskPercent,
  MAX_RISK_PERCENT: MONEY_MANAGEMENT.setupRiskPercent,
  MAX_DAILY_LOSS_PERCENT: MONEY_MANAGEMENT.dailyLossLimitPercent,
  DAILY_RISK_TIMEZONE: "UTC",
  DAILY_BASELINE_CAPTURE_GRACE_SECONDS: "300",
  INCLUDE_UNREALIZED_IN_DAILY_LOSS: "true",
  MIN_RISK_REWARD_RATIO: "0.5",
  MAX_SLIPPAGE_BPS: "2",
  MAX_SLIPPAGE_POINTS: "5",
  MAX_SPREAD_POINTS: "10",
  MAX_SPREAD_ATR_RATIO: "0.10",
  MAX_SPREAD_PERCENTILE: "95",
  SPREAD_PERCENTILE_MINIMUM_SAMPLES: "30",
  SPREAD_SESSION_ABNORMAL_MULTIPLIER: "3",
  MAX_ORDERS_PER_DAY: "100",
  ORDER_EXPIRY_MIN_SECONDS: "60",
  ORDER_EXPIRY_MAX_SECONDS: "120",
  PREFERRED_ORDER_EXPIRY_SECONDS: "60",
  MIN_STOP_DISTANCE_POINTS: "",
  MAX_STOP_DISTANCE_ATR: "3",
  MAX_ENTRY_DISTANCE_ATR: "2.5",
  ENTRY_LATENCY_BUFFER_ATR: "0.25",
  PREFERRED_MAX_ENTRY_DISTANCE_ATR: "0.75",
  MAX_MARGIN_USAGE_PERCENT: "1",
  PAPER_ACCOUNT_EQUITY: "10000",
  PAPER_ACCOUNT_BALANCE: "10000",
  PAPER_AVAILABLE_MARGIN: "10000",
  PAPER_MARGIN_PER_NATIVE_VOLUME: "1",
  PAPER_SLIPPAGE_POINTS: "0",
  DATABASE_POOL_MIN: "1",
  DATABASE_POOL_MAX: "10",
  LOCAL_LOG_MAX_SIZE_MB: "20",
  LOCAL_LOG_MAX_FILES: "10",
  SERVER_STATS_INTERVAL_SECONDS: "10",
  NETWORK_INTERFACE: "",
  TRUST_PROXY: "false",
  STRATEGY_VERSION: "0.2.2-fixed-risk.4",
  CODE_VERSION: "0.2.2-fixed-risk.4",
  MODEL_INPUT_PROFILE: "structured",
  MAX_DRAWDOWN_PERCENT: MONEY_MANAGEMENT.drawdownLimitPercent,
} as const;

export const OPERATOR_KEYS = [
  "ACCOUNT_ID",
  "ACCOUNT_KEY",
  "AI_API_KEY",
  "AI_BASE_URL",
  "AI_MODEL",
  "AUTOMATIC_ANALYSIS_ENABLED",
  "BETTERSTACK_INGESTING_HOST",
  "BETTERSTACK_SOURCE_TOKEN",
  "CTRADER_ACCESS_TOKEN",
  "CTRADER_CLIENT_ID",
  "CTRADER_CLIENT_SECRET",
  "CTRADER_REFRESH_TOKEN",
  "DASHBOARD_CONTROL_TOKEN",
  "DATABASE_URL",
  "DEMO_TRADING_ACKNOWLEDGEMENT",
  "DEMO_TRADING_ENABLED",
  "EMERGENCY_STOP",
  "INSTANCE_ID",
  "MAX_POSITION_NOTIONAL",
  "TRADING_MODE",
  "TRADING_SYMBOL",
] as const;
export const DEPLOYMENT_KEYS = [
  "AI_ORCHESTRATOR_PORT",
  "ANALYTICS_PORT",
  "API_PORT",
  "APP_ENV",
  "CTRADER_ACCESS_TOKEN_EXPIRES_AT",
  "CTRADER_API_HOST",
  "CTRADER_API_PORT",
  "CTRADER_CONNECTION_MODE",
  "CTRADER_TOKEN_STATE_FILE",
  "CTRADER_TOKEN_URL",
  "DASHBOARD_PORT",
  "DATABASE_SSL_MODE",
  "EMERGENCY_STOP_FILE",
  "HOST",
  "LIVE_ENABLEMENT_FILE",
  "LOCAL_LOG_DIR",
  "MARKET_DATA_PORT",
] as const;
export const BROKER_DISCOVERED_KEYS = [
  "ACCOUNT_CURRENCY",
  "SYMBOL_ID",
  "ACCOUNT_TYPE",
  "SYMBOL_DISCOVERY_ENABLED",
] as const;
export const OBSOLETE_KEYS = [
  "ACCOUNT_EQUITY_FLOOR",
  "AI_MAX_INPUT_TOKENS",
  "AI_STRICT_JSON",
  "APP_NAME",
  "ATR_SMOOTHING",
  "BETTERSTACK_HEARTBEAT_URL",
  "EMA_SOURCE",
  "GH_PAT",
  "GH_REPO",
  "GH_USER",
  "LOSS_COOLDOWN_SECONDS",
  "MAX_OPEN_POSITIONS_PER_SYMBOL",
  "MAX_PENDING_ORDERS_PER_SYMBOL",
  "METRICS_ENABLED",
  "METRICS_PORT",
  "ORDER_BOOK_AGGREGATION_ENABLED",
  "ORDER_BOOK_AGGREGATION_WINDOWS",
  "ORDER_BOOK_IMBALANCE_ENABLED",
  "OTEL_EXPORTER_OTLP_ENDPOINT",
  "OTEL_EXPORTER_OTLP_HEADERS",
  "REALIZED_VOLATILITY_ENABLED",
  "SESSION_VWAP_ENABLED",
  "SHADOW_MODE",
  "SPREAD_FEATURES_ENABLED",
  "SPREAD_FILTER_MODE",
  "SWING_STRUCTURE_ENABLED",
  "TIMEZONE",
  "VOLUME_FEATURES_ENABLED",
  "VWAP_ENABLED",
] as const;

export function resolveRuntimeEnvironment(
  source: NodeJS.ProcessEnv,
): NodeJS.ProcessEnv {
  const conflicts: string[] = [];
  for (const [key, value] of Object.entries(FIXED_DEFAULTS)) {
    const legacy = source[key];
    if (legacy !== undefined && legacy !== "" && legacy !== value)
      conflicts.push(key);
  }
  if (source.USE_COMPLETED_CANDLES_ONLY === "false")
    conflicts.push("USE_COMPLETED_CANDLES_ONLY");
  for (const key of BROKER_DISCOVERED_KEYS)
    if (source[key]) conflicts.push(key);
  if (source.SHADOW_MODE !== undefined && source.SHADOW_MODE !== "")
    conflicts.push("SHADOW_MODE");
  // Credentials, endpoints and populated environment files are never rewritten.
  if (conflicts.length)
    throw new Error(
      `CONFIG_POLICY_CONFLICT:${[...new Set(conflicts)].sort().join(",")}:remove legacy overrides after reviewing docs/configuration.md`,
    );
  if (
    source.CTRADER_CONNECTION_MODE &&
    !["demo", "live"].includes(source.CTRADER_CONNECTION_MODE)
  )
    throw new Error("CONFIG_CONNECTION_MODE_INVALID");
  if (source.DATABASE_SSL_MODE === "disable" && source.TRADING_MODE !== "paper")
    throw new Error("CONFIG_BROKER_DATABASE_TLS_REQUIRED");
  const resolved: NodeJS.ProcessEnv = {
    ...source,
    ...FIXED_DEFAULTS,
    CTRADER_API_HOST:
      source.CTRADER_API_HOST ||
      ((source.CTRADER_CONNECTION_MODE ||
        (source.TRADING_MODE === "shadow" ? "live" : "demo")) === "live"
        ? "live.ctraderapi.com"
        : "demo.ctraderapi.com"),
    CTRADER_API_PORT: source.CTRADER_API_PORT || "5036",
    CTRADER_CONNECTION_MODE:
      source.CTRADER_CONNECTION_MODE ||
      (source.TRADING_MODE === "shadow" ? "live" : "demo"),
    BETTERSTACK_ENABLED:
      source.BETTERSTACK_SOURCE_TOKEN && source.BETTERSTACK_INGESTING_HOST
        ? "true"
        : "false",
  };
  // Removed by explicit operator policy change. A cached legacy floor has no authority.
  delete resolved.ACCOUNT_EQUITY_FLOOR;
  return resolved;
}
